/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BuaKeoBao;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Client extends javax.swing.JFrame implements Runnable {

    Socket socket;
    DataInputStream inStream;
    DataOutputStream outStream;
    int enemy;

    public Client() {
        initComponents();
        try {
            socket = new Socket("localHost", 3456);
            inStream = new DataInputStream(socket.getInputStream());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error Connection");
        }
        Thread thread = new Thread(this);
        thread.start();
        time();
        timeRandom();
        timeOut();
    }

    public void run() {
        try {
            while (true) {
                try {
                    Thread.sleep(500);
                } catch (Exception ex) {
                }
                String line = inStream.readUTF();
                String z = "[0-9]{1}-----";
                if (line.matches(z)) {
                    enemy = Integer.parseInt(line.charAt(0) + "");
                    if (enemy == 1) {
                        jLabelBKBenemy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/game/bua.png")));
                    } else if (enemy == 2) {
                        jLabelBKBenemy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/game/keo.png")));
                    } else if (enemy == 3) {
                        jLabelBKBenemy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/game/bao.png")));
                    }
                } else {
                    text.setText(text.getText() + "Enemy : " + line + "\n");
                }
            }
        } catch (IOException ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        textSend = new javax.swing.JTextField();
        Send = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelBKBenemy = new javax.swing.JLabel();
        jLabelBKBme = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jButtonRandom = new javax.swing.JButton();
        jButtonUp = new javax.swing.JButton();
        jLabelGoalme = new javax.swing.JLabel();
        jLabelGoalenemy = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client");

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 48)); // NOI18N
        jLabel10.setText("Rock-paper-scissors");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/other/dialogsun.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/game/buaShow.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/game/keoShow.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/game/baoShow.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel12)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanel2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/avatar/avatar6.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 410, 32, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/avatar/avatar2.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 0, 32, 40);

        text.setEditable(false);
        text.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(text);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(360, 60, 300, 340);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("Messerger ");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(430, 0, 180, 50);

        textSend.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel2.add(textSend);
        textSend.setBounds(360, 410, 240, 40);

        Send.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/other/send.png"))); // NOI18N
        Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendActionPerformed(evt);
            }
        });
        jPanel2.add(Send);
        Send.setBounds(610, 410, 50, 40);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setText("Nguyễn Kết Đoàn");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(70, 410, 190, 40);

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel5.setText("Nguyễn Kết Đoàn");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(70, 0, 190, 40);

        jLabelBKBenemy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/game/question-mark.png"))); // NOI18N
        jPanel2.add(jLabelBKBenemy);
        jLabelBKBenemy.setBounds(110, 250, 130, 130);

        jLabelBKBme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/game/question-mark.png"))); // NOI18N
        jPanel2.add(jLabelBKBme);
        jLabelBKBme.setBounds(110, 60, 130, 130);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(30, 220, 240, 10);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\game\\src\\Image\\other\\round.png")); // NOI18N
        jLabel8.setFocusable(false);
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel8.setPreferredSize(new java.awt.Dimension(110, 110));
        jPanel2.add(jLabel8);
        jLabel8.setBounds(270, 175, 90, 90);

        time.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        time.setForeground(new java.awt.Color(0, 0, 0));
        time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time.setText("20");
        jPanel2.add(time);
        time.setBounds(290, 190, 50, 60);

        jButtonRandom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/other/random.png"))); // NOI18N
        jButtonRandom.setBorder(null);
        jButtonRandom.setBorderPainted(false);
        jButtonRandom.setFocusPainted(false);
        jButtonRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRandomActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonRandom);
        jButtonRandom.setBounds(300, 60, 40, 40);

        jButtonUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/other/tien.png"))); // NOI18N
        jButtonUp.setBorder(null);
        jButtonUp.setBorderPainted(false);
        jButtonUp.setFocusPainted(false);
        jButtonUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonUp);
        jButtonUp.setBounds(300, 120, 40, 40);

        jLabelGoalme.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabelGoalme.setForeground(new java.awt.Color(102, 153, 255));
        jLabelGoalme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/other/kg.png"))); // NOI18N
        jLabelGoalme.setText("0");
        jLabelGoalme.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabelGoalme);
        jLabelGoalme.setBounds(0, 160, 65, 50);

        jLabelGoalenemy.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabelGoalenemy.setForeground(new java.awt.Color(102, 153, 255));
        jLabelGoalenemy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/other/kg.png"))); // NOI18N
        jLabelGoalenemy.setText("0");
        jLabelGoalenemy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabelGoalenemy);
        jLabelGoalenemy.setBounds(0, 230, 65, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(680, 602));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int i = 0;

    void time() {
        if (i == 0) {
            try {
                Thread.sleep(400);
                i = 1 ;
            } catch (Exception ex) {}
        }
        Thread thread1 = new Thread() {
            public void run() {
                while (!time.getText().equals("0")) {
                    try {
                        Thread.sleep(1020);
                        int t = Integer.parseInt(time.getText());
                        time.setText((t - 1) + "");
                    } catch (Exception ex) {
                        System.out.println("Time !!!");
                    }
                }
            }
        };
        thread1.start();
    }

    void timeRandom() {
        Thread thread = new Thread() {
            public void run() {
                while (true) {
                    try {
                        Thread.sleep(800);
                    } catch (Exception ex) {
                    }
                    if (time.getText().equals("10") && tien == 0) {
                        jButtonRandom.doClick();
                        jButtonUp.doClick();
                        break;
                    }
                }
            }
        };
        thread.start();
    }

    void Wrap() {
        if (tien == 1) {
            tien = 3;
        } else if (tien == 2) {
            tien = 1;
        } else if (tien == 3) {
            tien = 2;
        }
    }

    void timeOut() {
        Thread thread = new Thread() {
            public void run() {
                while (true) {
                    try {
                        Thread.sleep(1000);
                    } catch (Exception ex) {
                    }
                    if (time.getText().equals("0")) {
                        Wrap();
                        send(tien + "-----");
                        try {
                            Thread.sleep(2000);
                        } catch (Exception ex) {
                        }
                        System.out.println("Enemy Client " + enemy);
                        ResultJDialog dialog = new ResultJDialog(Client.this, false);
                        dialog.setTitle("Client");
                        if ((tien == 3 && enemy == 1) || (tien == 2 && enemy == 3) || (tien == 1 && enemy == 2)) {
                            dialog.icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/game/winJDialog.png")));
                            dialog.text.setText("Win");
                            jLabelGoalme.setText(Integer.parseInt(jLabelGoalme.getText()) + 1 + "");
                        } else if (tien == enemy) {
                            dialog.icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/game/drawnJDialog.png")));
                            dialog.text.setText("Drawn");
                        } else {
                            dialog.icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/game/loseJDialog.png")));
                            dialog.text.setText("Lose");
                            jLabelGoalenemy.setText(Integer.parseInt(jLabelGoalenemy.getText()) + 1 + "");
                        }
                        dialog.setVisible(true);
                        try {
                            Thread.sleep(7000);
                            time.setText("15");
                            jLabelBKBme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/game/question-mark.png")));
                            jLabelBKBenemy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/game/question-mark.png")));
                            tien = 0;
                            //read();
                            time();
                            timeRandom();
                            timeOut();
                        } catch (Exception ex) {
                        }
                        break;
                    }
                }
            }
        };
        thread.start();
    }

    void send(String a) {
        try {
            outStream = new DataOutputStream(socket.getOutputStream());
            outStream.writeUTF(a);
            outStream.flush();
            textSend.setText("");
        } catch (IOException ex) {
        }
    }
    private void SendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendActionPerformed
        text.setText(text.getText() + "Me : " + textSend.getText() + "\n");
        send(textSend.getText());
    }//GEN-LAST:event_SendActionPerformed

    private void jButtonRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRandomActionPerformed
        Thread thread1 = new Thread() {
            public void run() {
                int x = 18 + new Random().nextInt(3);
                for (int i = 1; i <= 12; i++) {
                    try {
                        Thread.sleep(80);
                        jButtonUp.doClick();
                    } catch (Exception ex) {
                        System.out.println("Slow please !!!");
                    }
                }
                for (int i = 13; i <= 17; i++) {
                    try {
                        Thread.sleep(200);
                        jButtonUp.doClick();
                    } catch (Exception ex) {
                        System.out.println("Slow please !!!");
                    }
                }
                for (int i = 18; i <= x; i++) {
                    try {
                        Thread.sleep(400);
                        jButtonUp.doClick();
                    } catch (Exception ex) {
                        System.out.println("Slow please !!!");
                    }
                }

            }
        };
        thread1.start();
    }//GEN-LAST:event_jButtonRandomActionPerformed

    private void jButtonUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpActionPerformed
        if (tien == 0) {
            tien = 1;
        }
        if (tien == 1) {
            jLabelBKBme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/game/bua.png")));
            tien = 2;
        } else if (tien == 2) {
            jLabelBKBme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/game/keo.png")));
            tien = 3;
        } else if (tien == 3) {
            jLabelBKBme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/game/bao.png")));
            tien = 1;
        }
    }//GEN-LAST:event_jButtonUpActionPerformed
    int tien = 0;

    void Wrap(int a, int b, int c) {
        if (tien == 1) {
            tien = a;
        } else if (tien == 2) {
            tien = b;
        } else if (tien == 3) {
            tien = c;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Send;
    private javax.swing.JButton jButtonRandom;
    private javax.swing.JButton jButtonUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelBKBenemy;
    private javax.swing.JLabel jLabelBKBme;
    private javax.swing.JLabel jLabelGoalenemy;
    private javax.swing.JLabel jLabelGoalme;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextPane text;
    private javax.swing.JTextField textSend;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
